apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: backstage/sample
spec:
  type: service
  owner: user:guest
  lifecycle: experimental